apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        # service-api container configuration
        - name: service-api
          resources:
            limits:
              # changed the limits to half of the default
              cpu: "1000m" # Up to 2 full cores
            requests:
              cpu: "500m" # Use 1 full cores
